[package]
name = "z_primitive_roots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divisors = "0.2.1"
flume = "0.10.14"
libm = "0.2.6"
number-theory = "0.0.23"
